# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Piráti Týn nad Vltavou
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tyn.pirati.cz" # the base hostname & protocol for your site, e.g. http://example.com

# Loccalhost setting
baseurl: ""
theme: jekyll-theme-pirati

# Github pages setting
#baseurl: "example.pirati.cz" # the subpath of your site, e.g. /blog
#remote_theme: jitka/jekyll-theme-pirati



# Build settings
markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /program/:path/

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "page"
      rbar: "foto"
  -
    scope:
      path: "_program"
    values:
      layout: "page"
      rbar: "volby-2018"
calendar: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=kddvdvu3adcjef2kro4j6mm838%40group.calendar.google.com&amp;color=%232952A3&amp;ctz=Europe%2FPrague
fb: https://www.facebook.com/PiratiTyn/
tw: PiratskaStrana
instagramm: https://www.instagram.com/pirati.cz/
gplus: https://plus.google.com/u/0/+piratskastrana
emptyArray: []
